[package]
name = "babbelaar"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1"
self_cell = "1"
strum = { version = "0.26", features = ["derive"] }

log = "0.4"

[dev-dependencies]
rstest = "0.21"
